#!/bin/bash

. /usr/share/conjure-up/hooklib/common.sh

debug "Setting Blog URL to $BLOGURL"

exposeResult "Visit your Ghost application at $BLOGURL or if that fails http://$(unitAddress haproxy 0)" 0 "true"
